#!/bin/bash

set -e

# export PACKER_LOG=1
rm railsbridge-iso_virtualbox.box || true
packer build -only virtualbox-iso packer.json
mv packer_virtualbox-iso_virtualbox.box railsbridge-iso_virtualbox.box
vagrant box remove railsbridge_mtl_201304 || true
vagrant box add railsbridge_mtl_201304 railsbridge-iso_virtualbox.box
