#!/bin/bash

set -e

#export PACKER_LOG=1
rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso packer.json
vagrant box remove railsbridge_mtl_201304 || true
vagrant box add railsbridge_mtl_201304 packer_virtualbox-iso_virtualbox.box
